steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF_Credential'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'd044120trial'
      space: 'dev'
      manifest: 'cfManifest.yaml'